apiVersion: v1
kind: ConfigMap
metadata:
  name: future-suite-config
  namespace: future-suite-qa
data:
  ENV: "prod"
  DEPLOY_ENV: "staging"
  PORT: "8080"
  APP_DISPLAY_NAME: "Future Suite (QA)"
  APP_IDENTIFIER: "future-suite-qa"
